<?php

return [

    'roles' => [
        'administrador' => ['aliases' => ['adm', 'adm.', 'admin', 'administrador']],
        'gerente'       => ['aliases' => ['gerente', 'ger.']],
        'contador'      => ['aliases' => ['contador', 'contab', 'contab.']],
        'jefe_obra'     => ['aliases' => ['jefe_obra', 'j.obra', 'jefe de obra', 'jefe obra']],
        'logistica'     => ['aliases' => ['logistica', 'logist', 'logist.']],
        'rrhh'          => ['aliases' => ['rrhh', 'recursos humanos']],
        'cliente'       => ['aliases' => ['cliente']],
        'lector'        => ['aliases' => ['lector']],
    ],

    'finanzas' => [
        'pago', 'pago_cliente', 'pago_proveedor', 'pago_empleado',
        'pago_proyecto', 'cuotas_pago', 'pagos_cancelados',
    ],

    'obra' => [
        'asignacion_empleado', 'asignacion_maquinaria', 'registro_horas',
        'registro_horas_diario', 'paralizacion', 'paralizacion_obra', 'uso_material',
    ],

    'compras' => [
        'material', 'proveedor', 'compra', 'detalle_compra', 'inventario',
    ],

    'rrhh_tables' => ['empleado', 'feriado'],

    'cliente_tables' => [
        'cliente', 'contrato', 'proyecto', 'cuotas_pago',
        'obras_terminadas', 'documento', 'permiso', 'notificaciones', 'resumen_costos',
    ],

    'lector_tables' => [
        'ciudad', 'cliente', 'contrato', 'proyecto', 'obras_terminadas',
    ],

    'jefe_obra_insert_only' => [
        'obras_terminadas', 'mantenimiento', 'documento', 'permiso',
    ],

    'global_read_roles' => ['gerente', 'contador', 'jefe_obra', 'logistica', 'rrhh'],

    'route_tables' => [
        'dashboard' => null,
        'operativa.clientes.index' => 'cliente',
        'operativa.proyectos.index' => 'proyecto',
        'operativa.asistencia.index' => 'registro_horas',
        'operativa.asistencia.create' => 'registro_horas',
        'operativa.paralizaciones.index' => 'paralizacion',
        'operativa.finalizadas.index' => 'obras_terminadas',
        'operativa.ciudades.index' => 'ciudad',
        'operativa.ciudades.create' => 'ciudad',
        'operativa.ciudades.store' => 'ciudad',
        'operativa.ciudades.edit' => 'ciudad',
        'operativa.ciudades.update' => 'ciudad',
        'operativa.ciudades.destroy' => 'ciudad',
        'operativa.contratos.index' => 'contrato',
        'operativa.contratos.create' => 'contrato',
        'operativa.contratos.store' => 'contrato',
        'operativa.contratos.show' => 'contrato',
        'operativa.contratos.edit' => 'contrato',
        'operativa.contratos.update' => 'contrato',
        'operativa.contratos.destroy' => 'contrato',
        'operativa.compras.index' => 'compra',
        'operativa.compras.create' => 'compra',
        'operativa.compras.store' => 'compra',
        'operativa.compras.show' => 'compra',
        'operativa.compras.edit' => 'compra',
        'operativa.compras.update' => 'compra',
        'operativa.compras.destroy' => 'compra',
        'operativa.cotizaciones.index' => 'cotizacion',
        'operativa.cotizaciones.create' => 'cotizacion',
        'operativa.cotizaciones.store' => 'cotizacion',
        'operativa.cotizaciones.edit' => 'cotizacion',
        'operativa.cotizaciones.update' => 'cotizacion',
        'operativa.cotizaciones.destroy' => 'cotizacion',
        'operativa.cuotas.index' => 'cuotas_pago',
        'operativa.cuotas.create' => 'cuotas_pago',
        'operativa.cuotas.store' => 'cuotas_pago',
        'operativa.cuotas.edit' => 'cuotas_pago',
        'operativa.cuotas.update' => 'cuotas_pago',
        'operativa.cuotas.destroy' => 'cuotas_pago',
        'operativa.maquinarias.catalogo' => 'maquinaria',
        'operativa.maquinarias.catalogo_create' => 'maquinaria',
        'operativa.maquinarias.catalogo_store' => 'maquinaria',
        'operativa.maquinarias.catalogo_edit' => 'maquinaria',
        'operativa.maquinarias.catalogo_update' => 'maquinaria',
        'operativa.maquinarias.catalogo_destroy' => 'maquinaria',
        'operativa.maquinarias.index' => 'asignacion_maquinaria',
        'operativa.maquinarias.create' => 'asignacion_maquinaria',
        'operativa.maquinarias.store' => 'asignacion_maquinaria',
        'operativa.maquinarias.edit' => 'asignacion_maquinaria',
        'operativa.maquinarias.update' => 'asignacion_maquinaria',
        'operativa.maquinarias.destroy' => 'asignacion_maquinaria',
        'operativa.proveedores.index' => 'proveedor',
        'operativa.proveedores.create' => 'proveedor',
        'operativa.proveedores.store' => 'proveedor',
        'operativa.proveedores.edit' => 'proveedor',
        'operativa.proveedores.update' => 'proveedor',
        'operativa.proveedores.destroy' => 'proveedor',
        'rrhh.empleados.index' => 'empleado',
        'rrhh.empleados.create' => 'empleado',
        'rrhh.empleados.store' => 'empleado',
        'rrhh.empleados.edit' => 'empleado',
        'rrhh.empleados.update' => 'empleado',
        'rrhh.empleados.destroy' => 'empleado',
        'rrhh.asignaciones.index' => 'asignacion_empleado',
        'rrhh.pagos.index' => 'pago_empleado',
        'rrhh.permisos.index' => 'permiso',
        'rrhh.feriados.index' => 'feriado',
        'reportes.costos.index' => 'resumen_costos',
        'reportes.alertas.index' => 'notificaciones',
        'reportes.alertas.marcar-todas' => 'notificaciones',
        'reportes.alertas.marcar-leida' => 'notificaciones',
        'reportes.alertas.eliminar' => 'notificaciones',
        'reportes.log.index' => 'log_cambios',
        'configuracion.usuarios.index' => 'usuario',
        'configuracion.usuarios.create' => 'usuario',
        'configuracion.usuarios.store' => 'usuario',
        'configuracion.usuarios.edit' => 'usuario',
        'configuracion.usuarios.update' => 'usuario',
        'configuracion.usuarios.destroy' => 'usuario',
        'configuracion.usuarios.restaurar' => 'usuario',
    ],

    'menu' => [
        ['route' => 'operativa.clientes.index', 'table' => 'cliente', 'label' => 'Clientes'],
        ['route' => 'operativa.contratos.index', 'table' => 'contrato', 'label' => 'Contratos'],
        ['route' => 'operativa.proyectos.index', 'table' => 'proyecto', 'label' => 'Proyectos'],
        ['route' => 'operativa.cotizaciones.index', 'table' => 'cotizacion', 'label' => 'Cotizaciones'],
        ['route' => 'operativa.cuotas.index', 'table' => 'cuotas_pago', 'label' => 'Cuotas de Pago'],
        ['route' => 'operativa.compras.index', 'table' => 'compra', 'label' => 'Compras'],
        ['route' => 'operativa.proveedores.index', 'table' => 'proveedor', 'label' => 'Proveedores'],
        ['route' => 'operativa.maquinarias.index', 'table' => 'asignacion_maquinaria', 'label' => 'Maquinaria'],
        ['route' => 'operativa.ciudades.index', 'table' => 'ciudad', 'label' => 'Ciudades'],
        ['route' => 'operativa.asistencia.index', 'table' => 'registro_horas', 'label' => 'Control de Horas'],
        ['route' => 'operativa.paralizaciones.index', 'table' => 'paralizacion', 'label' => 'Paralizaciones'],
        ['route' => 'operativa.finalizadas.index', 'table' => 'obras_terminadas', 'label' => 'Obras Finalizadas'],
    ],

    'menu_rrhh' => [
        ['route' => 'rrhh.empleados.index', 'table' => 'empleado', 'label' => 'Maestro Empleados'],
        ['route' => 'rrhh.asignaciones.index', 'table' => 'asignacion_empleado', 'label' => 'Asignaciones'],
        ['route' => 'rrhh.pagos.index', 'table' => 'pago_empleado', 'label' => 'Pagos / Planillas'],
        ['route' => 'rrhh.permisos.index', 'table' => 'permiso', 'label' => 'Permisos / Trámites'],
        ['route' => 'rrhh.feriados.index', 'table' => 'feriado', 'label' => 'Feriados', 'icon' => 'fas fa-calendar-day'],
    ],

];
